export * from "./navbar";
export * from "./hero";
export * from "./companies";
export * from "./courses";
export * from "./achivements";
export * from "./categories";
export * from "./feedbacks";
export * from "./cta";
export * from "./footer";
